### ISSUE TITLE
感觉内容不错，希望有一篇完整的文章描述如何使用它来开发

### ISSUE THREAD

**Issue by profileCaren** [ylfeng250/vue-crx#1]
如题

**Comment by ylfeng250** [comment]
谢谢对这个项目的肯定，我当时写这个模板是自己临时需要使用，所以暂时没有考虑维护，等有时间了会考虑优化和维护到时候应该会有文章，你可以去[掘金](https://juejin.im/search?query=vue%20chrome&utm_source=gold_browser_extension&utm_medium=search)上搜一下有相关的文章。
我的思路主要是配置webpack，Chrome扩展有自己的模板目录，所以配置了一个多文件入口的webpack打包，另外配了代码压缩等一些常见的打包配置，没有其他什么东西了。
至于Chrome开发readme中有参考链接，挺详细的。

**Comment by profileCaren** [comment]
@ylfeng250 资料自然都可以查啦。anyway，谢谢你的贡献，我关掉这个 issue 啦
